######################################################################
# Automatically generated by qmake (3.1) Sat Jun 21 23:41:26 2025
######################################################################

SOURCES += hello.cpp
TEMPLATE = app

QT += qml
TARGET = demo
isEmpty(PREFIX) {
  PREFIX = /usr/local
}

target.path = $$PREFIX/bin
INSTALLS += target

INCLUDEPATH += .

QT += gui
QT += widgets
