[microphone]
sample_rate = 16000
output_sample_rate = 24000
channels = 1
format = "paInt16"
chunk_size = 1024
silence_threshold = 1000
[voicetotext]
model = "openai/whisper-large-v3"
[texttotext]
model = "NovaSky-AI/Sky-T1-32B-Preview"
[texttovoice]
model = "suno/bark"
args = "v2/en_speaker_6"
